# Generated by Django 4.2.11 on 2026-04-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auditevent_geo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Header History',
                'verbose_name_plural': 'Header History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('analysis_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis History',
                'ordering': ['-created_at'],
            },
        ),
    ]
