services:
  flask-backend:
    build:
      context: .
      dockerfile: docker/flask.Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - mongodb

  express-gateway:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - flask-backend
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
