services:
  flask-backend:
    container_name: afya-backend
    build:
      context: ..
      dockerfile: docker/flask.Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ${ENV_FILE:-../.env}
    volumes:
      - ../backend:/app
      - ../uploads:/app/uploads
    depends_on:
      - mongodb

  express-gateway:
    container_name: afya-gateway
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
    ports:
      - "4000:4005"
    env_file:
      - ${ENV_FILE:-../.env}
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - flask-backend
      - mongodb

  mongodb:
    container_name: afya-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
